apiVersion: v1
kind: Service
metadata:
  name: store-engine-dto-validator-ms-service
spec:
  selector:
    app: store-engine-dto-validator-ms
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3002
  type: NodePort
